version: '3'

services:
  
  #############################
  # Kafka + ZooKeeper
  #############################
  kafka:
    image: spotify/kafka
    container_name: kafka
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
    ports:
      - "9092:9092"
      - "2181:2181"

  #############################
  # DotNetCore Kafka Producer
  #############################
  kafka-producer:
    build: ./kafka-producer
    container_name: kafka-producer
    command: dotnet run
    depends_on:
      - kafka

  #############################
  # DotNetCore Kafka Consumer
  #############################
  kafka-consumer:
    build: ./kafka-consumer
    container_name: kafka-consumer
    command: dotnet run
    depends_on:
      - kafka